version: '3.8'

services:
  loki:
    image: grafana/loki:2.9.1
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
      - ./start-loki.sh:/usr/bin/start-loki.sh
    environment:
      - VAULT_ADDR=http://<vault-server>:8200
      - VAULT_TOKEN=<vault-token>
    command: /usr/bin/start-loki.sh

  promtail:
    image: grafana/promtail:2.9.1
    volumes:
      - /var/log:/var/log
      - /var/run/docker.sock:/var/run/docker.sock
      - ./promtail-config.yaml:/etc/promtail/config.yml

  grafana:
    image: grafana/grafana:9.5.2
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  grafana_data:
